<%@ page language="java" isELIgnored="false" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>

<div id="footer">
<!--<span class="footer"> 	Generated by <a href="http://www.myeclipseide.com/spring.php">MyEclipse for Spring</a> | Copyright &copy; 2011 All Rights Reserved </span>-->

<!-- <p align="right"> -->
		Company Name © All rights Reseverd | Design by  <a href="http://w3layouts.com">W3Layouts</a> 
<!-- </p> -->
 </div>
	
<!-- end footer --> 

